name: preview deployment
on:
    workflow_dispatch:

jobs:
    call-deploy:
        uses: ./.github/workflows/_deploy-reusable.yaml
        permissions:
            contents: write
        with:
            is_prod: false
            skip_db: false
        secrets:
            DB_URL: ${{ secrets.DB_PREVIEW_URL }}
            DB_AUTH_TOKEN: ${{ secrets.DB_PREVIEW_AUTH_TOKEN }}
            DB_HTTP_URL: ${{ secrets.DB_PREVIEW_HTTP_URL }}
            DB_AUTH_TOKEN_HTTP: ${{ secrets.DB_PREVIEW_AUTH_TOKEN_HTTP }}
            INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
